name: whatsapp-for-linux
base: core18
grade: stable
confinement: strict
adopt-info: whatsapp-for-linux

parts:
  whatsapp-for-linux:
    source-type: local
    source: .
    plugin: cmake
    override-pull: |
      snapcraftctl pull
      version=$(cat "build/release/generated/VERSION")
      snapcraftctl set-version $version
      sed -i.bak -e 's|Icon=${WFL_ICON}|Icon=share/icons/hicolor/256x256/apps/${WFL_ICON}.png|g' resource/desktop/com.github.eneshecan.WhatsAppForLinux.desktop.in
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - build-essential
      - libxml2-utils
      - libgtkmm-3.0-dev
      - libwebkit2gtk-4.0-dev
      - libayatana-appindicator3-dev
    stage-packages:
      - libgtkmm-3.0-1v5
      - libayatana-appindicator3-1
      - glib-networking
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-libav
    parse-info: [share/metainfo/com.github.eneshecan.WhatsAppForLinux.appdata.xml]

slots:
  dbus-app:
    interface: dbus
    bus: session
    name: com.github.eneshecan.WhatsAppForLinux

apps:
  whatsapp-for-linux:
    command: bin/whatsapp-for-linux
    desktop: share/applications/com.github.eneshecan.WhatsAppForLinux.desktop
    common-id: com.github.eneshecan.WhatsAppForLinux
    extensions: [gnome-3-28]  # This takes care of most of the things for us
    plugs:
      - network
      - network-manager
      - network-manager-observe
      - browser-support
      - camera
      - audio-playback
      - audio-record
      - home
      - removable-media
      - opengl
      - upower-observe
      - screen-inhibit-control
    slots:
      - dbus-app
