name: Install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential libgtkmm-3.0-dev libwebkit2gtk-4.0-dev libappindicator3-dev

      - name: Configure
        run: mkdir build

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j4

      - name: Install
        run: |
          cd build
          sudo make install
