name: Install

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential intltool libgtkmm-3.0-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev libcanberra-dev

      - name: Configure
        run: mkdir build

      - name: Build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
          make -j4

      - name: Install
        run: |
          cd build
          sudo make install
