name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint clang-format
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: './src'
          extensions: 'hpp,cpp'
          clangFormatVersion: 15
